remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: "KY American Chestnuts"
author: Steve Hartman

navbar-links:
  About: "aboutme"
  Blog: "/"
  American Chestnuts: "/pages/americanchestnuts"
  Other Resources:
    - Projects: "projects"

social-network-links:
  email: "hartman@nctc.com"
  telephone: +12702377325
  youtube:

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "chestnuts,american chestnuts,farming,farms"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

edit_page_button: false

timezone: "America/Chicago"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

url-pretty: "hartmanhardwoods.github.io"
url-canonical: https://hartmanhardwoods.github.io

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# 2fc73a3a967e97599c9763d05e564189d5
